// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BattleGrid: typeof import('./components/battle/BattleGrid.vue')['default']
    BattleSquare: typeof import('./components/battle/BattleSquare.vue')['default']
    ColorPicker: typeof import('./components/colors/ColorPicker.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Login: typeof import('./components/auth/Login.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
